google_analytics: UA-160716658-1
plugins:
  - jekyll-redirect-from
  - jekyll-last-modified-at
kramdown:
  footnote_backlink: ↑
last-modified-at:
  date-format: '%Y-%m-%d'
sass:
  sass_dir: _sass
url: https://utelecon.adm.u-tokyo.ac.jp
lang: ja
title: utelecon
repository: utelecon/utelecon.github.io
twitter:
  card: summary
defaults:
  -
    scope:
      path: ""
    values:
      lang: ja
      image: /assets/images/ogp.png
      toc: true
  -
    scope:
      path: en
    values:
      lang: en
      image: /assets/images/ogp.png
      toc: true
  -
    scope:
      path: articles
    values:
      updated_at: true
  -
    scope:
      path: en/articles
    values:
      updated_at: true
