google_analytics: UA-160716658-1
plugins:
    - jekyll-redirect-from
sass:
    sass_dir: _sass
lang: ja
title: utelecon
repository: utelecon/utelecon.github.io
defaults:
  -
    scope:
      path: en
    values:
      lang: en